export type Employee = {
  id: string
  name: string
  age: number
  joinDate: string
  startTime: string
  active: boolean
  department: string
}

export const sampleData: ReadonlyArray<Employee> = [
  {
    id: '1',
    name: 'Tanaka Taro',
    age: 28,
    joinDate: '2022-04-01',
    startTime: '09:00',
    active: true,
    department: 'Engineering',
  },
  {
    id: '2',
    name: 'Suzuki Hanako',
    age: 32,
    joinDate: '2020-01-15',
    startTime: '08:30',
    active: true,
    department: 'Sales',
  },
  {
    id: '3',
    name: 'Yamada Jiro',
    age: 45,
    joinDate: '2015-06-01',
    startTime: '10:00',
    active: false,
    department: 'HR',
  },
  {
    id: '4',
    name: 'Sato Yuki',
    age: 24,
    joinDate: '2024-04-01',
    startTime: '09:30',
    active: true,
    department: 'Engineering',
  },
  {
    id: '5',
    name: 'Takahashi Ren',
    age: 38,
    joinDate: '2018-09-01',
    startTime: '08:00',
    active: true,
    department: 'Finance',
  },
  {
    id: '6',
    name: 'Watanabe Mei',
    age: 29,
    joinDate: '2021-07-15',
    startTime: '09:00',
    active: true,
    department: 'Engineering',
  },
  {
    id: '7',
    name: 'Ito Kaito',
    age: 51,
    joinDate: '2010-04-01',
    startTime: '08:30',
    active: true,
    department: 'Sales',
  },
  {
    id: '8',
    name: 'Nakamura Aoi',
    age: 26,
    joinDate: '2023-10-01',
    startTime: '10:00',
    active: true,
    department: 'HR',
  },
  {
    id: '9',
    name: 'Kobayashi Hina',
    age: 33,
    joinDate: '2019-03-15',
    startTime: '09:00',
    active: false,
    department: 'Finance',
  },
  {
    id: '10',
    name: 'Kato Sota',
    age: 41,
    joinDate: '2016-01-10',
    startTime: '08:00',
    active: true,
    department: 'Engineering',
  },
  {
    id: '11',
    name: 'Yoshida Riko',
    age: 27,
    joinDate: '2022-08-01',
    startTime: '09:30',
    active: true,
    department: 'Sales',
  },
  {
    id: '12',
    name: 'Yamamoto Haruto',
    age: 36,
    joinDate: '2017-11-01',
    startTime: '09:00',
    active: true,
    department: 'Engineering',
  },
  {
    id: '13',
    name: 'Matsumoto Sakura',
    age: 23,
    joinDate: '2025-04-01',
    startTime: '10:00',
    active: true,
    department: 'HR',
  },
  {
    id: '14',
    name: 'Inoue Yuto',
    age: 48,
    joinDate: '2012-05-15',
    startTime: '08:30',
    active: false,
    department: 'Finance',
  },
  {
    id: '15',
    name: 'Kimura Mio',
    age: 30,
    joinDate: '2021-01-10',
    startTime: '09:00',
    active: true,
    department: 'Sales',
  },
  {
    id: '16',
    name: 'Hayashi Rui',
    age: 34,
    joinDate: '2019-06-01',
    startTime: '08:00',
    active: true,
    department: 'Engineering',
  },
  {
    id: '17',
    name: 'Shimizu Yuna',
    age: 25,
    joinDate: '2024-01-15',
    startTime: '09:30',
    active: true,
    department: 'HR',
  },
  {
    id: '18',
    name: 'Saito Akira',
    age: 55,
    joinDate: '2008-04-01',
    startTime: '08:00',
    active: true,
    department: 'Finance',
  },
  {
    id: '19',
    name: 'Ogawa Koharu',
    age: 31,
    joinDate: '2020-09-01',
    startTime: '09:00',
    active: true,
    department: 'Engineering',
  },
  {
    id: '20',
    name: 'Murakami Daiki',
    age: 42,
    joinDate: '2014-02-01',
    startTime: '10:00',
    active: false,
    department: 'Sales',
  },
]
